package main;

import ventanas.VentanaPrincipal;

/*
 * PRACTICA APLICACION DE ESCRITORIO:
 * SIGUIENDOVLOS CONCEPTOS Y EJEMPLOS MOSTRADOS CREAR UNA APLICACION DE GESTION PARA UN NEGOCIO
 * EN EL CUAL SE GESTIONEN INFORMACIONES SOBRE CLIENTES Y PRODUCTOS, EL PRODUCTO SERA EL DEL NEGOCIO
 * A ELEGIR POR EL PROGRAMADOR, DEBERÁ TENER AL MENOS 7 CAMPOS, Y DEBERÁ ESTAR ALMACENADO ENUNA TABLA
 * DE BASE DE DATOS.
 * 
 * LA GESTION DEBERA PERMITIR:
 * REGISTRAR, LISTAR, EDITAR Y BORRARNINFORMACIONES. PERO EN ESTA PARTE SOLO SERÁ NECESARIO REGISTRAR.
 * 
 * OPCIONALES:
 * USAR 3 CAMPOS DE ENTRADA NO ENSEÑADOS EN CLASE PARA EL PRODUCTO A ELEGIR.
 * (p.ej: checkbox, lista desplegable, radiobuttons)
 * 
 * intentar realizar un listado de informaciones en los paneles de listado*/

public class Principal {
	public static void main(String[] args) {
		new VentanaPrincipal();
	}

}
